### ISSUE TITLE
curl installed but not recognised

### ISSUE THREAD

**Issue by ahnkle** [webguerilla/wordpress-sitemapgenerator#1]
I installed Sitemap Generator v1.3.1 with Wordpress 4.5.2.

I got a message 

> cURL is not activated on your webspace.

I installed the php plugin but it is still complaining. I can see the plugin installed when I look at phpinfo().

Is there anything I need to set up?

**Comment by marcobeierer** [comment]
Hi ahnkle,

The sitemap generator uses the function [curl_version](https://secure.php.net/manual/en/function.curl-version.php) to determine if curl is installed. This function should always be available if curl is installed.

Have you restarted your webserver after installing the php plugin?

Best regards,
Marco
